---
- name: Install
  hosts: localhost
  # hosts:
  #   localhost:
  #     vars:
  #       ansible_connection: local
  #       ansible_python_interpreter: "{{ansible_playbook_python}}"
  # gather_facts: no
  vars:
    bin_dir: "{{ '/opt/homebrew/bin' if ansible_os_family == 'Darwin' else '/usr/local/bin' }}"
    login_shell: "{{ bin_dir }}/fish"
    common_files:
      - { src: fish, dest: ~/.config/fish }
      - { src: starship.toml, dest: ~/.config/starship.toml }
      - { src: .tmux.conf, dest: ~/.tmux.conf }
      - { src: .vimrc, dest: ~/.vimrc }
      - { src: .gitconfig, dest: ~/.gitconfig }
      - { src: .mackup.cfg, dest: ~/.mackup.cfg }
      - { src: .mackup, dest: ~/.mackup }
      - { src: .zshrc, dest: ~/.zshrc }
      - { src: .bashrc, dest: ~/.bashrc }
    mac_files:
      - { src: .hushlogin, dest: ~/.hushlogin }
      - { src: Brewfile, dest: ~/.Brewfile }
      - { src: .gnupg/pinentry-wrapper, dest: /usr/local/bin/pinentry-wrapper, become: true }
      - { src: .gnupg/gpg-agent.conf, dest: ~/.gnupg/gpg-agent.conf }
      - { src: .gnupg/gpg.conf, dest: ~/.gnupg/gpg.conf }
    sublime_files:
      - { src: sublime/Package Control.sublime-settings, dest: Packages/User/Package Control.sublime-settings }
      - { src: sublime/Preferences.sublime-settings, dest: Packages/User/Preferences.sublime-settings }
    sublime_mac_dir: ~/Library/Application Support/Sublime Text 3/
    sublime_linux_dir: ~/.config/sublime-text-3/
  tasks:
    # - name: Install required system packages
    #   apt:
    #     name:
    #       - htop
    #       - vim
    #       - rsync
    #     update_cache: yes
    #     cache_valid_time: 86400 # One day
    #     state: present
    #   tags: [setup]

    - block:
        - name: make sure destination dir exists
          file: path={{ item.dest | dirname }} state=directory # recurse=yes
          loop: "{{ common_files }}"
        - name: copy files
          file: src={{ playbook_dir }}/{{ item.src }} dest={{ item.dest }} state=link
          loop: "{{ common_files }}"
      tags: [setup]

    - block:
        - name: macOS | make sure destination dir exists
          file: path={{ item.dest | dirname }} state=directory # recurse=yes
          when: (item.become | default(false) | bool) == false
          loop: "{{ mac_files }}"
        - name: macOS | copy files
          file: src={{ playbook_dir }}/{{ item.src }} dest={{ item.dest }} state=link
          # become: "{{ (item.become | default(false) | bool) == true }}"
          when: (item.become | default(false) | bool) == false
          loop: "{{ mac_files }}"

        - name: macOS | make sure destination dir exists
          file: path={{ item.dest | dirname }} state=directory # recurse=yes
          when: (item.become | default(false) | bool) == true
          become: true
          loop: "{{ mac_files }}"
        - name: macOS | copy files
          file: src={{ playbook_dir }}/{{ item.src }} dest={{ item.dest }} state=link
          become: true
          when: (item.become | default(false) | bool) == true
          loop: "{{ mac_files }}"
      when: ansible_os_family == "Darwin"
      tags: [setup]

    - block:
        - name: macOS | sublime | make sure destination dir exists
          file: path={{ sublime_mac_dir + item.dest | dirname }} state=directory # recurse=yes
          loop: "{{ sublime_files }}"
        - name: macOS | sublime | copy files
          file: src={{ playbook_dir }}/{{ item.src }} dest={{ sublime_mac_dir + item.dest }} state=link
          loop: "{{ sublime_files }}"
      when: ansible_os_family == "Darwin"
      tags: [setup]

    - block:
        - name: arch | sublime | make sure destination dir exists
          file: path={{ sublime_mac_dir + item.dest | dirname }} state=directory # recurse=yes
          loop: "{{ sublime_files }}"
        - name: arch | sublime | copy files
          file: src={{ playbook_dir }}/{{ item.src }} dest={{ sublime_mac_dir + item.dest }} state=link
          loop: "{{ sublime_files }}"
      when: ansible_os_family == "Archlinux"
      tags: [setup]

    # Add shells installed via homebrew on macOS to /etc/shells
    - block:
        - name: check if homebrew bash is installed
          stat: path={{ bin_dir }}/bash
          register: brew_bash
        - name: add homwbrew bash to /etc/shells
          lineinfile: dest=/etc/shells line="{{ bin_dir }}/bash" state=present
          when: brew_bash.stat.exists

        - name: check if homebrew zsh is installed
          stat: path={{ bin_dir }}/zsh
          register: brew_zsh
        - name: add homwbrew zsh to /etc/shells
          lineinfile: dest=/etc/shells line="{{ bin_dir }}/zsh" state=present
          when: brew_zsh.stat.exists

        - name: check if homebrew fish is installed
          stat: path={{ bin_dir }}/fish
          register: brew_fish
        - name: add homwbrew fish to /etc/shells
          lineinfile: dest=/etc/shells line="{{ bin_dir }}/fish" state=present
          when: brew_fish.stat.exists
      when: ansible_os_family == "Darwin"
      become: true

    - name: check if preferred login_shell is installed
      stat: path={{ login_shell }}
      register: login_shell_installed

    - name: Set default shell
      user: name={{ ansible_user_id }} shell={{ login_shell }}
      when: login_shell_installed.stat.exists
      become: true
