version: 3

tasks:
  _decrypt-config:
    cmds:
      - bash -c '(cd secrets && nix run github:ryantm/agenix -- -d config.json.age) > config.json' && git add config.json
    internal: true

  print-config:
    cmds:
      - cd secrets && nix run github:ryantm/agenix -- -d config.json.age

  edit-config:
    cmds:
      - cd secrets && nix run github:ryantm/agenix -- -e config.json.age

  init:
    cmds:
      - task: _decrypt-config
      - defer: git rm -f config.json
      - nix run nix-darwin -- switch --flake ~/dotfiles {{ .CLI_ARGS }}
      - chsh -s /run/current-system/sw/bin/fish

  switch:
    cmds:
      - task: _decrypt-config
      - defer: git rm -f config.json
      - darwin-rebuild switch --flake ~/dotfiles {{ .CLI_ARGS }}

  nixos:switch:
    cmds:
      - task: _decrypt-config
      - defer: git rm -f config.json
      - sudo nixos-rebuild switch --flake ~/dotfiles#hp-chromebox {{ .CLI_ARGS }}

  # nixos vscode remote target - https://github.com/microsoft/vscode-remote-release/issues/103#issuecomment-1060907227, https://github.com/microsoft/vscode-remote-release/issues/648#issuecomment-503148523
  switch-nixos-remote:
    cmds:
      - task: _decrypt-config
      - defer: git rm -f config.json
      - nixos-rebuild --use-remote-sudo --fast --build-host blesswinsamuel@homelab-hp-chromebox-wifi --target-host blesswinsamuel@homelab-hp-chromebox-wifi switch --flake ~/dotfiles#hp-chromebox {{ .CLI_ARGS }}

  maintanence:
    cmds:
      - nix store gc
