#!/usr/bin/env bash

if [[ -f "/opt/homebrew/bin/pinentry-mac" ]]; then
    exec /opt/homebrew/bin/pinentry-mac "$@"
elif [[ -f "/usr/local/bin/pinentry-mac" ]]; then
    exec /usr/local/bin/pinentry-mac "$@"
fi
