#!/usr/bin/env bash

################################
# Shows current brightness
#
# dependencies:
# - xbacklight
#
# @return {Number}: Current brightness
################################

case $BLOCK_BUTTON in
  # scroll up
  # raise brightness
  4) $HOME/.config/i3/scripts/brightness.sh up ;;

  # scroll down
  # lower brightness
  5) $HOME/.config/i3/scripts/brightness.sh down ;;
esac

printf "%.0f%%" "$(xbacklight -get)"
