#!/usr/bin/env bash

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	buffers=$2
}
/^Cached:/ {
	cached=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	mem_free = mem_free + cached
	mem_used = mem_total - mem_free
    printf("%.2fG S %.1fG\n", mem_used/1024/1024, (swap_total-swap_free)/1024/1024)
    printf("%.1fG\n", mem_used/1024/1024)
    if ((mem_free / mem_total) < 0.2)
        printf("#FF4444")
}
' /proc/meminfo
