directory: ~/Music
library: library.db
import:
  # beet import $source -> doesn't copy, move, or write tagged metadata to file - only stored in beets library db
  # songs in the library reference source directory paths

  # beet move -c[-p] -> actually move imported files (in db) from $source to $dest
  # songs in the library reference destination directory paths
  # acts as a library consolidator: items matching the query are renamed into your library directory structure
  # beet move [-c] -> copy instead of move
  # beet move [-d <destination dir>] query -> move items matching a query to anywhere in filesystem
  # beet move [-t] - timid mode which will ask again before really moving or copying the files.

  # beet update [-p] -> update library (and optionally move files) to reflect metadata changes in individual files and file deletions
  # Update metadata from FILES/ONLINE -> LIBRARY

  # beet write [-p] -> actually write library info to individual files

  copy: no # copy files into the library directory when using beet import
  move: no # move files into the library directory when using beet import
  write: no # metadata (e.g., ID3) tags are written to files when using beet import

  incremental: yes # imported directories are recorded and these recorded directories are skipped in next import
  autotag: no
  bell: yes # ring the terminal bell to get your attention when the importer needs your input.
  log: beetsimport.log # importer’s log
ui:
  color: yes
paths:
  default: $albumartist/%if{$year,$year - }$album/%if{$multidisc,Disc $disc/}$track - $title
  singleton: Non-Album/%if{$year,$year - }$artist/$title
  comp: Compilations/%if{$year,$year - }$album%aunique{}/$track - $title
item_fields: # for inline plugin - multi disc albums
  multidisc: 1 if disctotal > 1 else 0
plugins: web convert play info badfiles inline
convert:
  never_convert_lossy_files: yes
  dest: ~/Music (MP3)
  command: ffmpeg -i $source -y -c:v copy -c:a libmp3lame -q:a 0 $dest
  extension: mp3
play:
  command: nvlc
web:
  host: 0.0.0.0
  