[tools]
biome = "latest"
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "latest"
pulumi = "latest"
uv = "latest"
crane = "latest"
opencode = "latest"
claude = "latest"
"pipx:hermes-agent" = "latest"
"github:can1357/oh-my-pi" = "latest"
"cargo:https://github.com/blesswinsamuel/pretty-log" = "latest"
"npm:@openchamber/web" = "latest"
pnpm = "latest"
"npm:@getpaseo/cli" = "latest"
antigravity-cli = "latest"
buf = "latest"
codex = "latest"
gh = "latest"
process-compose = "latest"
terraform = "latest"
rust = "latest"
